version: '3'

services:
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=artush
        - POSTGRES_PASSWORD=asana_db
        - POSTGRES_NAME=postgres
  web:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/asana_task
    ports:
      - "8000:8000"
    depends_on:
      - db